# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
- checkout: self

- task: Cache@2
  displayName: Cache npm
  inputs:
    key: $(Build.SourcesDirectory)/package-lock.json
    path: $(npm_config_cache)

- script: npm install --quiet --no-progress --cache=$(npm_config_cache)
- task: gulp@0
  inputs:
    gulpFile: 'gulpfile.js'
    targets: 'lint'
    gulpjs: 'node_modules/gulp/bin/gulp.js'
    enableCodeCoverage: false

- task: gulp@0
  inputs:
    gulpFile: 'gulpfile.js'
    targets: 'build'
    gulpjs: 'node_modules/gulp/bin/gulp.js'
    enableCodeCoverage: false

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'public/_'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true